In [1]:
import numpy as np

Test_a = np.array ([41, 56417, 32156])
Test_b = np.array([[5341, 2.45946, 641], [4, 5, 6]])

print(type(Test_a),"Форма:", Test_a.shape, "Массив a:",Test_a) # количество строк и столбцов (shape)
print(type(Test_b), "Форма:", Test_b.shape)
print("Массив b:\n",Test_b)

<class 'numpy.ndarray'> Форма: (3,) Массив a: [   41 56417 32156]
<class 'numpy.ndarray'> Форма: (2, 3)
Массив b:
 [[5.34100e+03 2.45946e+00 6.41000e+02]
 [4.00000e+00 5.00000e+00 6.00000e+00]]


In [2]:
# Создаём массив из обычного списка
list = [1, 2, 3, 4, 5]
c = np.array(list)

# Создаём массив из вложенного списка
list_1 = [[1, 2], [3, 4]]
d = np.array(list_1)

# Созданём массивы с помощью встроенных функций
zeros_ = np.zeros(5)          # массив, состоящий из 5 нулей
ones_ = np.ones((2, 3))       # двумерный массив 2x3, состоящий из единиц
range_ = np.arange(0, 10, 2)  # массив с шагом 2

print("Массив из списка:", c)
print("Двумерный массив из вложенного списка:\n", d)
print("Массив из нулей:", zeros_)
print("Массив из единиц:\n", ones_)
print("Массив с шагом 2:", range_)

Массив из списка: [1 2 3 4 5]
Двумерный массив из вложенного списка:
 [[1 2]
 [3 4]]
Массив из нулей: [0. 0. 0. 0. 0.]
Массив из единиц:
 [[1. 1. 1.]
 [1. 1. 1.]]
Массив с шагом 2: [0 2 4 6 8]


In [3]:
print("Форма:", ones_.shape)     # количество строк и столбцов (shape) массива из единиц
print("Тип данных (dtype):", ones_.dtype)  # тип элементов

Форма: (2, 3)
Тип данных (dtype): float64


In [4]:
arr = np.array([1, 2, 3, 4, 5])

element_3 = arr[2]  # третий элемент, так как индексация с 0
print("Элемент с индексом 2:", element_3)

subarray = arr[1:4]  # элементы с индексами 1, 2, 3, а элемент 4 не входит
print("Срез [1:4]:", subarray)

# По аналогии с двумерным массивом
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Элемент [1, 2] (вторая строка, третий столбец):", arr2d[1, 2])
print("Первая строка:", arr2d[0, :])
print("Второй столбец:", arr2d[:, 1])

Элемент с индексом 2: 3
Срез [1:4]: [2 3 4]
Элемент [1, 2] (вторая строка, третий столбец): 6
Первая строка: [1 2 3]
Второй столбец: [2 5 8]


In [5]:
a = np.array([1, 2, 3]) # оба массива одной формы
b = np.array([4, 5, 6])

# Складываем и перемножаем элементы массивов поэлементно (тавтология, но не сташно)
sum_ab = a + b
mult_ab = a * b

print("Сложение:", sum_ab)
print("Умножение:", mult_ab)

Сложение: [5 7 9]
Умножение: [ 4 10 18]


In [6]:
mean_value = a.mean()  # среднее арифметическое элементов массива
sum_value = b.sum()    # сумма всех элементов массива

print("Среднее значение массива a:", mean_value)
print("Сумма элементов массива b:", sum_value)

Среднее значение массива a: 2.0
Сумма элементов массива b: 15
